# -*- coding: utf-8 -*-
"""model to deploy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VX8LSOf2YrryBkj8lNxVP8j1XfCLPC_J
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

df = pd.read_csv('salary.csv')

df.isnull().sum()

df.info()

"""# filling with mean"""

df['test_score'].fillna(df['test_score'].mean(),inplace=True)
df['interview_score'].fillna(df['interview_score'].mean(),inplace=True)

df['experience'].fillna(0, inplace=True)

def to_num(str):
  dict = { 'zero':0, 'one':1, 'two' : 2, 'three':3, 'four':4, 'five':5, 'six':6, 'seven':7, 
          'eight':8, 'nine':9, 'ten':10, 'eleven':11,'twelve':12, 0:0, 'thirteen':13, 'fifteen':15 }
  return dict[str]

df['experience'] = df['experience'].apply(lambda x: to_num(x))
df

x = df.iloc[:,:3]
y = df.iloc[:,-1]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=.2, random_state=5)

from sklearn.linear_model import LinearRegression
mymodel = LinearRegression()

mymodel.fit(x_train,y_train)

y_pred = mymodel.predict(x_test)

y = mymodel.predict([[5,8,7]])
y

import pickle
pickle.dump(mymodel,open("model.pkl","wb"))